/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_12112024;


import java.awt.Color;
import java.awt.Font;
import java.util.HashSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanel_agregar = new javax.swing.JPanel();
        lbl_nombrePersona = new javax.swing.JLabel();
        lbl_correoPersona = new javax.swing.JLabel();
        txt_nombrePersona = new javax.swing.JTextField();
        txt_correoPersona = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        jpanel_verInfo = new javax.swing.JPanel();
        lbl_nombrePersonaInfo = new javax.swing.JLabel();
        txt_nombrePersonaInfo = new javax.swing.JTextField();
        txt_correoPersonaInfo = new javax.swing.JTextField();
        lbl_correoPersonaInfo = new javax.swing.JLabel();
        jcb_usuarios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_posSeleccionada = new javax.swing.JLabel();
        jpanel_editar = new javax.swing.JPanel();
        jcb_usuariosEditar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_nombrePersonaEditar = new javax.swing.JTextField();
        lbl_nombrePersonaEditar = new javax.swing.JLabel();
        txt_correoPersonaEditar = new javax.swing.JTextField();
        lbl_correoPersonaEditar = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        jpanel_eliminar = new javax.swing.JPanel();
        jcb_usuariosEliminar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jpanel_tables = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_mensaje = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jpanel_fuentes = new javax.swing.JPanel();
        lbl_etiquetaFuentes = new javax.swing.JLabel();
        btn_actualizarTamano = new javax.swing.JButton();
        btn_actualizarFuente = new javax.swing.JButton();
        btn_actualizarEstilo = new javax.swing.JButton();
        txt_tamanoFuente = new javax.swing.JTextField();
        txt_nombreFuente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcb_estiloFuente = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btn_actualizarBackground = new javax.swing.JButton();
        check_terminoYCondiciones = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jmb_menuPrincipal = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jm_submenu = new javax.swing.JMenu();
        jmi_elementoSubMenu = new javax.swing.JMenuItem();
        jm_editar = new javax.swing.JMenu();
        jmi_informacion = new javax.swing.JMenuItem();
        jmi_limpiar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setOpaque(true);

        jpanel_agregar.setBackground(new java.awt.Color(255, 204, 255));

        lbl_nombrePersona.setText("Nombre");

        lbl_correoPersona.setText("Correo");

        txt_nombrePersona.setText("jTextField1");

        txt_correoPersona.setText("jTextField1");

        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpanel_agregarLayout = new javax.swing.GroupLayout(jpanel_agregar);
        jpanel_agregar.setLayout(jpanel_agregarLayout);
        jpanel_agregarLayout.setHorizontalGroup(
            jpanel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_agregarLayout.createSequentialGroup()
                .addGroup(jpanel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_agregarLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jpanel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombrePersona)
                            .addComponent(lbl_correoPersona))
                        .addGap(48, 48, 48)
                        .addGroup(jpanel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombrePersona, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                            .addComponent(txt_correoPersona)))
                    .addGroup(jpanel_agregarLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(btn_agregar)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jpanel_agregarLayout.setVerticalGroup(
            jpanel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_agregarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jpanel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombrePersona)
                    .addComponent(txt_nombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpanel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_agregarLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lbl_correoPersona))
                    .addGroup(jpanel_agregarLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(txt_correoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(124, 124, 124)
                .addComponent(btn_agregar)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jpanel_agregar);

        jpanel_verInfo.setBackground(new java.awt.Color(255, 255, 204));

        lbl_nombrePersonaInfo.setText("Nombre");

        txt_nombrePersonaInfo.setText("jTextField1");

        txt_correoPersonaInfo.setText("jTextField1");

        lbl_correoPersonaInfo.setText("Correo");

        jcb_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_usuariosActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuarios");

        jLabel3.setText("Pos:");

        javax.swing.GroupLayout jpanel_verInfoLayout = new javax.swing.GroupLayout(jpanel_verInfo);
        jpanel_verInfo.setLayout(jpanel_verInfoLayout);
        jpanel_verInfoLayout.setHorizontalGroup(
            jpanel_verInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_verInfoLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(jpanel_verInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombrePersonaInfo)
                    .addComponent(lbl_correoPersonaInfo)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(48, 48, 48)
                .addGroup(jpanel_verInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_posSeleccionada)
                    .addGroup(jpanel_verInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jcb_usuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nombrePersonaInfo)
                        .addComponent(txt_correoPersonaInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)))
                .addGap(72, 72, 72))
        );
        jpanel_verInfoLayout.setVerticalGroup(
            jpanel_verInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_verInfoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jpanel_verInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(jpanel_verInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_posSeleccionada))
                .addGap(42, 42, 42)
                .addGroup(jpanel_verInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombrePersonaInfo)
                    .addComponent(txt_nombrePersonaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpanel_verInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_verInfoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lbl_correoPersonaInfo))
                    .addGroup(jpanel_verInfoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(txt_correoPersonaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver información", jpanel_verInfo);

        jcb_usuariosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_usuariosEditarActionPerformed(evt);
            }
        });

        jLabel4.setText("Usuarios");

        txt_nombrePersonaEditar.setText("jTextField1");

        lbl_nombrePersonaEditar.setText("Nombre");

        txt_correoPersonaEditar.setText("jTextField1");

        lbl_correoPersonaEditar.setText("Correo");

        btn_editar.setText("Editar");
        btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpanel_editarLayout = new javax.swing.GroupLayout(jpanel_editar);
        jpanel_editar.setLayout(jpanel_editarLayout);
        jpanel_editarLayout.setHorizontalGroup(
            jpanel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_editarLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jpanel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombrePersonaEditar)
                    .addComponent(lbl_correoPersonaEditar)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addGroup(jpanel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_usuariosEditar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nombrePersonaEditar)
                    .addComponent(txt_correoPersonaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
            .addGroup(jpanel_editarLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(btn_editar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_editarLayout.setVerticalGroup(
            jpanel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_editarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jpanel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_usuariosEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(95, 95, 95)
                .addGroup(jpanel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombrePersonaEditar)
                    .addComponent(txt_nombrePersonaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpanel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_editarLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lbl_correoPersonaEditar))
                    .addGroup(jpanel_editarLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(txt_correoPersonaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addComponent(btn_editar)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar", jpanel_editar);

        jpanel_eliminar.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setText("eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpanel_eliminarLayout = new javax.swing.GroupLayout(jpanel_eliminar);
        jpanel_eliminar.setLayout(jpanel_eliminarLayout);
        jpanel_eliminarLayout.setHorizontalGroup(
            jpanel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_eliminarLayout.createSequentialGroup()
                .addGroup(jpanel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_eliminarLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jcb_usuariosEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_eliminarLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButton1)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jpanel_eliminarLayout.setVerticalGroup(
            jpanel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_eliminarLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jcb_usuariosEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton1)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jpanel_eliminar);

        jpanel_tables.setBackground(new java.awt.Color(255, 204, 102));

        lbl_nombre.setText("Hola mundo");

        lbl_mensaje.setText("Hola mundo etiqueta perdida");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab1", jPanel2);

        jTabbedPane2.addTab("tab2", jTabbedPane3);

        javax.swing.GroupLayout jpanel_tablesLayout = new javax.swing.GroupLayout(jpanel_tables);
        jpanel_tables.setLayout(jpanel_tablesLayout);
        jpanel_tablesLayout.setHorizontalGroup(
            jpanel_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_tablesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lbl_mensaje)
                .addGap(523, 523, 523))
            .addGroup(jpanel_tablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_tablesLayout.setVerticalGroup(
            jpanel_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_tablesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jpanel_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(lbl_mensaje))
                .addGap(43, 43, 43)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tablas", jpanel_tables);

        lbl_etiquetaFuentes.setText("jLabel1");

        btn_actualizarTamano.setText("Actualizar");
        btn_actualizarTamano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarTamanoMouseClicked(evt);
            }
        });

        btn_actualizarFuente.setText("Actualizar");
        btn_actualizarFuente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarFuenteMouseClicked(evt);
            }
        });

        btn_actualizarEstilo.setText("Actualizar");
        btn_actualizarEstilo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarEstiloMouseClicked(evt);
            }
        });

        jLabel5.setText("Tamaño");

        jLabel6.setText("Nombre de la fuente");

        jcb_estiloFuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negrita", "Normal", "Cursivo" }));

        jLabel7.setText("Estilo de la fuente");

        btn_actualizarBackground.setText("Actualizar Color");
        btn_actualizarBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarBackgroundMouseClicked(evt);
            }
        });

        check_terminoYCondiciones.setText("Lei todos los terminos y condiciones");
        check_terminoYCondiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_terminoYCondicionesMouseClicked(evt);
            }
        });

        jRadioButton1.setText("Casado");

        jRadioButton2.setText("Soltero");

        javax.swing.GroupLayout jpanel_fuentesLayout = new javax.swing.GroupLayout(jpanel_fuentes);
        jpanel_fuentes.setLayout(jpanel_fuentesLayout);
        jpanel_fuentesLayout.setHorizontalGroup(
            jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_fuentesLayout.createSequentialGroup()
                .addGroup(jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_fuentesLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btn_actualizarBackground))
                    .addGroup(jpanel_fuentesLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_etiquetaFuentes, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpanel_fuentesLayout.createSequentialGroup()
                                .addGroup(jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(33, 33, 33)
                                .addGroup(jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcb_estiloFuente, 0, 121, Short.MAX_VALUE)
                                    .addComponent(txt_tamanoFuente)
                                    .addComponent(txt_nombreFuente))
                                .addGap(39, 39, 39)
                                .addGroup(jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_actualizarTamano)
                                    .addComponent(btn_actualizarFuente)
                                    .addComponent(btn_actualizarEstilo)))))
                    .addGroup(jpanel_fuentesLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addGroup(jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(check_terminoYCondiciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jpanel_fuentesLayout.setVerticalGroup(
            jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_fuentesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbl_etiquetaFuentes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_tamanoFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_actualizarTamano)))
                .addGap(18, 18, 18)
                .addGroup(jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btn_actualizarFuente))
                .addGap(18, 18, 18)
                .addGroup(jpanel_fuentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcb_estiloFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizarEstilo))
                .addGap(51, 51, 51)
                .addComponent(btn_actualizarBackground)
                .addGap(37, 37, 37)
                .addComponent(check_terminoYCondiciones)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fuentes", jpanel_fuentes);

        jm_archivo.setText("File");

        jm_submenu.setText("Sub Menu");

        jmi_elementoSubMenu.setText("Elemento del submenu");
        jm_submenu.add(jmi_elementoSubMenu);

        jm_archivo.add(jm_submenu);

        jmb_menuPrincipal.add(jm_archivo);

        jm_editar.setText("Edit");

        jmi_informacion.setText("Informacion");
        jmi_informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_informacionActionPerformed(evt);
            }
        });
        jm_editar.add(jmi_informacion);

        jmi_limpiar.setText("Limpiar");
        jmi_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_limpiarActionPerformed(evt);
            }
        });
        jm_editar.add(jmi_limpiar);

        jmb_menuPrincipal.add(jm_editar);

        setJMenuBar(jmb_menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        String nombre = txt_nombrePersona.getText();
        String correo = txt_correoPersona.getText();
        Persona p = new Persona(nombre,correo);
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)jcb_usuarios.getModel();
        modelo.addElement(p);
        jcb_usuarios.setModel(modelo);
        
        
         DefaultComboBoxModel modeloEditar = (DefaultComboBoxModel)jcb_usuariosEditar.getModel();
        modeloEditar.addElement(p);
        jcb_usuariosEditar.setModel(modeloEditar);
        
         DefaultComboBoxModel modeloEliminar = (DefaultComboBoxModel)jcb_usuariosEliminar.getModel();
        modeloEliminar.addElement(p);
        jcb_usuariosEliminar.setModel(modeloEliminar);
        

        JOptionPane.showMessageDialog(null, "Se creo el usuario exitosamente");
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void jcb_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_usuariosActionPerformed
        // TODO add your handling code here:
       int pos =  jcb_usuarios.getSelectedIndex();
       Persona personaSeleccionada = (Persona)jcb_usuarios.getSelectedItem();
       // concatenacion -> ""+pos
       lbl_posSeleccionada.setText(pos+"");
       txt_nombrePersonaInfo.setText(personaSeleccionada.getNombre());
       txt_correoPersonaInfo.setText(personaSeleccionada.getCorreo());
       
       personaSeleccionadaTemporal = personaSeleccionada;
                
    }//GEN-LAST:event_jcb_usuariosActionPerformed

    private void jcb_usuariosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_usuariosEditarActionPerformed
        int pos =  jcb_usuariosEditar.getSelectedIndex();
       Persona personaSeleccionada = (Persona)jcb_usuariosEditar.getSelectedItem();
       txt_nombrePersonaEditar.setText(personaSeleccionada.getNombre());
       txt_correoPersonaEditar.setText(personaSeleccionada.getCorreo());
       personaSeleccionadaTemporal = personaSeleccionada;
    }//GEN-LAST:event_jcb_usuariosEditarActionPerformed

    private void btn_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseClicked
        String nuevoNombre = txt_nombrePersonaEditar.getText();
        String nuevoCorreo = txt_correoPersonaEditar.getText();
        
        // 1) obteniendo el usuario que hay seleccionado actualmente en el combobox 
//         Persona personaSeleccionada = (Persona)jcb_usuariosEditar.getSelectedItem();
//         
//         personaSeleccionada.setCorreo(nuevoCorreo);
//         personaSeleccionada.setNombre(nuevoNombre);
         
    // 2) trabajar con una variable temporal
        personaSeleccionadaTemporal.setCorreo(nuevoCorreo);
        personaSeleccionadaTemporal.setNombre(nuevoNombre);
         JOptionPane.showMessageDialog(null, "Se actualizo el usuario exitosamente");
         
        
    }//GEN-LAST:event_btn_editarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int pos = jcb_usuariosEliminar.getSelectedIndex();
        jcb_usuariosEliminar.removeItemAt(pos);
        jcb_usuariosEditar.removeItemAt(pos);
        jcb_usuarios.removeItemAt(pos);
        JOptionPane.showMessageDialog(null, "Se elimino el usuario exitosamente");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jmi_informacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_informacionActionPerformed
         JOptionPane.showMessageDialog(null, "bienvenido al programa de los menus!!!! ");
    }//GEN-LAST:event_jmi_informacionActionPerformed

    private void jmi_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_limpiarActionPerformed
       txt_correoPersona.setText("");
       txt_correoPersonaEditar.setText("");
       txt_correoPersonaInfo.setText("");
       txt_nombrePersona.setText("");
       txt_nombrePersonaEditar.setText("");
       txt_nombrePersonaInfo.setText("");
    }//GEN-LAST:event_jmi_limpiarActionPerformed

    private void btn_actualizarBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarBackgroundMouseClicked
       // static 
        Color seleccionado = JColorChooser.showDialog(null,"Seleccione el color de la letra",Color.BLACK);
//        lbl_etiquetaFuentes.setForeground(Color.ORANGE); agregar el color manualmente 
        lbl_etiquetaFuentes.setForeground(seleccionado);
    }//GEN-LAST:event_btn_actualizarBackgroundMouseClicked

    private void btn_actualizarTamanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarTamanoMouseClicked
        // TODO add your handling code here:
        int size = Integer.parseInt(txt_tamanoFuente.getText());
        /*nombre,estilo,tamano*/
        String nombre = lbl_etiquetaFuentes.getFont().getFontName();
        int estilo = lbl_etiquetaFuentes.getFont().getStyle();
        Font fuente = new Font(nombre,estilo,size);
        lbl_etiquetaFuentes.setFont(fuente);
    }//GEN-LAST:event_btn_actualizarTamanoMouseClicked

    private void btn_actualizarFuenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarFuenteMouseClicked
       String nombre = txt_nombreFuente.getText();
       int estilo = lbl_etiquetaFuentes.getFont().getStyle();
       int size = lbl_etiquetaFuentes.getFont().getSize();
        Font fuente = new Font(nombre,estilo,size);
        lbl_etiquetaFuentes.setFont(fuente);
    }//GEN-LAST:event_btn_actualizarFuenteMouseClicked

    private void btn_actualizarEstiloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarEstiloMouseClicked
     //Negrita, Normal, Cursivo
     String nombre =  lbl_etiquetaFuentes.getFont().getFontName();
     int size = lbl_etiquetaFuentes.getFont().getSize();
     Font fuente;
        if(jcb_estiloFuente.getSelectedIndex()==0){
          fuente  = new Font(nombre,Font.BOLD,size);
     }else if(jcb_estiloFuente.getSelectedIndex()==1){
         fuente = new Font(nombre,Font.PLAIN,size);
     }else{
          fuente = new Font(nombre,Font.ITALIC,size);
     }
          lbl_etiquetaFuentes.setFont(fuente);
    }//GEN-LAST:event_btn_actualizarEstiloMouseClicked

    private void check_terminoYCondicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_terminoYCondicionesMouseClicked
        // TODO add your handling code here:
//        if (check_terminoYCondiciones.isSelected()) {
//                 btn_actualizarBackground.setEnabled(true);
//                  btn_actualizarEstilo.setEnabled(true);
//                  btn_actualizarFuente.setEnabled(true);
//                  btn_actualizarTamano.setEnabled(true);
//        }else{
//              btn_actualizarBackground.setEnabled(false);
//                  btn_actualizarEstilo.setEnabled(false);
//                  btn_actualizarFuente.setEnabled(false);
//                  btn_actualizarTamano.setEnabled(false);
//        }
            boolean isEnabled = check_terminoYCondiciones.isSelected();
                  btn_actualizarBackground.setEnabled(isEnabled);
                  btn_actualizarEstilo.setEnabled(isEnabled);
                  btn_actualizarFuente.setEnabled(isEnabled);
                  btn_actualizarTamano.setEnabled(isEnabled);
    }//GEN-LAST:event_check_terminoYCondicionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    private Persona personaSeleccionadaTemporal;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarBackground;
    private javax.swing.JButton btn_actualizarEstilo;
    private javax.swing.JButton btn_actualizarFuente;
    private javax.swing.JButton btn_actualizarTamano;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JCheckBox check_terminoYCondiciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JComboBox<String> jcb_estiloFuente;
    private javax.swing.JComboBox<String> jcb_usuarios;
    private javax.swing.JComboBox<String> jcb_usuariosEditar;
    private javax.swing.JComboBox<String> jcb_usuariosEliminar;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenu jm_editar;
    private javax.swing.JMenu jm_submenu;
    private javax.swing.JMenuBar jmb_menuPrincipal;
    private javax.swing.JMenuItem jmi_elementoSubMenu;
    private javax.swing.JMenuItem jmi_informacion;
    private javax.swing.JMenuItem jmi_limpiar;
    private javax.swing.JPanel jpanel_agregar;
    private javax.swing.JPanel jpanel_editar;
    private javax.swing.JPanel jpanel_eliminar;
    private javax.swing.JPanel jpanel_fuentes;
    private javax.swing.JPanel jpanel_tables;
    private javax.swing.JPanel jpanel_verInfo;
    private javax.swing.JLabel lbl_correoPersona;
    private javax.swing.JLabel lbl_correoPersonaEditar;
    private javax.swing.JLabel lbl_correoPersonaInfo;
    private javax.swing.JLabel lbl_etiquetaFuentes;
    private javax.swing.JLabel lbl_mensaje;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombrePersona;
    private javax.swing.JLabel lbl_nombrePersonaEditar;
    private javax.swing.JLabel lbl_nombrePersonaInfo;
    private javax.swing.JLabel lbl_posSeleccionada;
    private javax.swing.JTextField txt_correoPersona;
    private javax.swing.JTextField txt_correoPersonaEditar;
    private javax.swing.JTextField txt_correoPersonaInfo;
    private javax.swing.JTextField txt_nombreFuente;
    private javax.swing.JTextField txt_nombrePersona;
    private javax.swing.JTextField txt_nombrePersonaEditar;
    private javax.swing.JTextField txt_nombrePersonaInfo;
    private javax.swing.JTextField txt_tamanoFuente;
    // End of variables declaration//GEN-END:variables
}
