/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_25112024;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_menuAcciones = new javax.swing.JPopupMenu();
        Limpiar = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        jd_mostrarOpciones = new javax.swing.JDialog();
        btn_CambiarTexto = new javax.swing.JButton();
        txt_nuevoTexto = new javax.swing.JTextField();
        jd_etiqueta = new javax.swing.JDialog();
        lbl_etiquetaDialog = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btn_mostrarDialog = new javax.swing.JButton();
        lbl_mensaje = new javax.swing.JLabel();
        jp_panelPopUp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        lbl_resultados = new javax.swing.JLabel();

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jp_menuAcciones.add(Limpiar);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jp_menuAcciones.add(Guardar);

        btn_CambiarTexto.setText("cambiar");
        btn_CambiarTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_CambiarTextoFocusLost(evt);
            }
        });
        btn_CambiarTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CambiarTextoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_mostrarOpcionesLayout = new javax.swing.GroupLayout(jd_mostrarOpciones.getContentPane());
        jd_mostrarOpciones.getContentPane().setLayout(jd_mostrarOpcionesLayout);
        jd_mostrarOpcionesLayout.setHorizontalGroup(
            jd_mostrarOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mostrarOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_nuevoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_mostrarOpcionesLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(btn_CambiarTexto)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jd_mostrarOpcionesLayout.setVerticalGroup(
            jd_mostrarOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mostrarOpcionesLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(txt_nuevoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btn_CambiarTexto)
                .addGap(126, 126, 126))
        );

        jd_etiqueta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jd_etiquetaFocusLost(evt);
            }
        });

        lbl_etiquetaDialog.setText("Hola");

        javax.swing.GroupLayout jd_etiquetaLayout = new javax.swing.GroupLayout(jd_etiqueta.getContentPane());
        jd_etiqueta.getContentPane().setLayout(jd_etiquetaLayout);
        jd_etiquetaLayout.setHorizontalGroup(
            jd_etiquetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_etiquetaLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(lbl_etiquetaDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jd_etiquetaLayout.setVerticalGroup(
            jd_etiquetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_etiquetaLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lbl_etiquetaDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_mostrarDialog.setText("mostrar Dialog");
        btn_mostrarDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrarDialogMouseClicked(evt);
            }
        });

        lbl_mensaje.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btn_mostrarDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(lbl_mensaje)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lbl_mensaje)
                .addGap(62, 62, 62)
                .addComponent(btn_mostrarDialog)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dialogs", jPanel1);

        jp_panelPopUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_panelPopUpMouseClicked(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        lbl_resultados.setText("jLabel3");

        javax.swing.GroupLayout jp_panelPopUpLayout = new javax.swing.GroupLayout(jp_panelPopUp);
        jp_panelPopUp.setLayout(jp_panelPopUpLayout);
        jp_panelPopUpLayout.setHorizontalGroup(
            jp_panelPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_panelPopUpLayout.createSequentialGroup()
                .addGroup(jp_panelPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_panelPopUpLayout.createSequentialGroup()
                        .addGroup(jp_panelPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_panelPopUpLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1))
                            .addGroup(jp_panelPopUpLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(78, 78, 78)
                        .addGroup(jp_panelPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombre)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)))
                    .addGroup(jp_panelPopUpLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(lbl_resultados, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jp_panelPopUpLayout.setVerticalGroup(
            jp_panelPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_panelPopUpLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jp_panelPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jp_panelPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(lbl_resultados)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pop Up Menu", jp_panelPopUp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jp_panelPopUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_panelPopUpMouseClicked
            // 1) invoker: 
            // 2) x
            // 3) y 
        jp_menuAcciones.show(jp_panelPopUp, evt.getX(), evt.getY());
    }//GEN-LAST:event_jp_panelPopUpMouseClicked

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
      txt_nombre.setText("");
      txt_apellido.setText("");
      lbl_resultados.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
       lbl_resultados.setText(txt_nombre.getText() +" "+txt_apellido.getText());
    }//GEN-LAST:event_GuardarActionPerformed

    private void btn_mostrarDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarDialogMouseClicked
        // TODO add your handling code here:
        jd_mostrarOpciones.setVisible(true);
         this.setVisible(false);
        jd_mostrarOpciones.pack();
        jd_etiqueta.setVisible(true);
        jd_etiqueta.pack();
        txt_nuevoTexto.setText("Hola desde el jframe!");
        
        
    }//GEN-LAST:event_btn_mostrarDialogMouseClicked

    private void btn_CambiarTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CambiarTextoMouseClicked
        String nuevoTexto = txt_nuevoTexto.getText();
        lbl_mensaje.setText(nuevoTexto);
        lbl_etiquetaDialog.setText(nuevoTexto);
    }//GEN-LAST:event_btn_CambiarTextoMouseClicked

    private void btn_CambiarTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_CambiarTextoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_CambiarTextoFocusLost

    private void jd_etiquetaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jd_etiquetaFocusLost
        // TODO add your handling code here:
                this.setVisible(true);
    }//GEN-LAST:event_jd_etiquetaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenuItem Limpiar;
    private javax.swing.JButton btn_CambiarTexto;
    private javax.swing.JButton btn_mostrarDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_etiqueta;
    private javax.swing.JDialog jd_mostrarOpciones;
    private javax.swing.JPopupMenu jp_menuAcciones;
    private javax.swing.JPanel jp_panelPopUp;
    private javax.swing.JLabel lbl_etiquetaDialog;
    private javax.swing.JLabel lbl_mensaje;
    private javax.swing.JLabel lbl_resultados;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nuevoTexto;
    // End of variables declaration//GEN-END:variables
}
