/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_6_11_2024;

import javax.swing.JOptionPane;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        //CREEA TODOS LOS ELEMENTOS VISUALES
        initComponents();
        // Despues del init componenets, TODOS los elementos visuales se han creado. 
        mostrarOpcionesAgregar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcb_opciones = new javax.swing.JComboBox<>();
        lbl_opciones = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_carrera = new javax.swing.JLabel();
        lbl_numCuenta = new javax.swing.JLabel();
        lbl_contacto = new javax.swing.JLabel();
        txt_numCuenta = new javax.swing.JTextField();
        txt_carrera = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_contacto = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_listar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcb_opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar", "Listar", "Modificar", "Eliminar" }));
        jcb_opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_opcionesActionPerformed(evt);
            }
        });

        lbl_opciones.setText("Opciones");

        lbl_nombre.setText("Nombre");

        lbl_carrera.setText("Carrera");

        lbl_numCuenta.setText("Numero cuenta");

        lbl_contacto.setText("Contacto");

        btn_agregar.setText("Agregar");

        btn_eliminar.setText("Eliminar");

        btn_listar.setText("Listar");

        btn_modificar.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_agregar)
                        .addGap(40, 40, 40)
                        .addComponent(btn_eliminar)
                        .addGap(45, 45, 45)
                        .addComponent(btn_listar)
                        .addGap(48, 48, 48)
                        .addComponent(btn_modificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_numCuenta)
                                .addComponent(lbl_carrera, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_contacto, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lbl_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_numCuenta)
                            .addComponent(txt_carrera)
                            .addComponent(txt_nombre)
                            .addComponent(txt_contacto)
                            .addComponent(jcb_opciones, 0, 358, Short.MAX_VALUE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_opciones)
                    .addComponent(jcb_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_numCuenta)
                    .addComponent(txt_numCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_carrera)
                    .addComponent(txt_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_contacto)
                    .addComponent(txt_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_listar)
                    .addComponent(btn_modificar))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_opcionesActionPerformed
        // TODO add your handling code here:
        /*
        0 Agregar
        1 Listar
        2 Modificar
        3 Eliminar
        */
        System.out.println("Selected index: "+jcb_opciones.getSelectedIndex());
        System.out.println("Selected Item: "+jcb_opciones.getSelectedItem());
        int opcion = jcb_opciones.getSelectedIndex();
        switch (opcion) {
            case 0 ->{ //agregar 
                mostrarOpcionesAgregar();
            }
            case 1 ->{//listar
                mostrarOpcionesListar();
            }
            case 2 ->{//modificar
                mostrarOpcionesModificar();
            }
            case 3->{ //eliminar
                mostrarOpcionesEliminar();
            }
            default ->{
                JOptionPane.showMessageDialog(null, "Opción no valida");
            }
        }
    }//GEN-LAST:event_jcb_opcionesActionPerformed
        public void mostrarOpcionesEliminar(){
        txt_nombre.setVisible(false);
        txt_numCuenta.setVisible(true);
        txt_numCuenta.setEnabled(true);
        txt_contacto.setVisible(false);
        txt_carrera.setVisible(false);
        
        lbl_nombre.setVisible(false);
        lbl_numCuenta.setVisible(true);
        lbl_contacto.setVisible(false);
        lbl_carrera.setVisible(false);
        
        btn_eliminar.setVisible(true);
        btn_modificar.setVisible(false);
        btn_listar.setVisible(false);
        btn_agregar.setVisible(false);
        
    }
        
    public void mostrarOpcionesListar(){
        txt_nombre.setVisible(false);
        txt_numCuenta.setVisible(true);
        txt_numCuenta.setEnabled(true);
        txt_contacto.setVisible(false);
        txt_carrera.setVisible(false);
        
        lbl_nombre.setVisible(false);
        lbl_numCuenta.setVisible(true);
        lbl_contacto.setVisible(false);
        lbl_carrera.setVisible(false);
        
        btn_eliminar.setVisible(false);
        btn_modificar.setVisible(false);
        btn_listar.setVisible(true);
        btn_agregar.setVisible(false);
        
    }
    public void mostrarOpcionesModificar(){
        //mostrando text fields
        txt_nombre.setVisible(true);
        txt_numCuenta.setVisible(true);
        txt_contacto.setVisible(true);
        txt_carrera.setVisible(true);
        //bloquear el numero de cuenta para que no podamos editar el valor que hay dentro. 
        txt_numCuenta.setEnabled(false);
        // ocultando botones para otras opciones
        btn_eliminar.setVisible(false);
        btn_agregar.setVisible(false);
        btn_listar.setVisible(false);
        btn_modificar.setVisible(true);
        
        lbl_nombre.setVisible(true);
        lbl_numCuenta.setVisible(true);
        lbl_contacto.setVisible(true);
        lbl_carrera.setVisible(true);
    }
    public void mostrarOpcionesAgregar(){
        //mostrando text fields
        txt_nombre.setVisible(true);
        txt_numCuenta.setVisible(true);
        txt_contacto.setVisible(true);
        txt_carrera.setVisible(true);
        //habilitar el textfield de numero de cuenta 
        txt_numCuenta.setEnabled(true);
        // ocultando botones para otras opciones
        btn_eliminar.setVisible(false);
        btn_modificar.setVisible(false);
        btn_listar.setVisible(false);
        btn_agregar.setVisible(true);
        
        lbl_nombre.setVisible(true);
        lbl_numCuenta.setVisible(true);
        lbl_contacto.setVisible(true);
        lbl_carrera.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_listar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> jcb_opciones;
    private javax.swing.JLabel lbl_carrera;
    private javax.swing.JLabel lbl_contacto;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_numCuenta;
    private javax.swing.JLabel lbl_opciones;
    private javax.swing.JTextField txt_carrera;
    private javax.swing.JTextField txt_contacto;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numCuenta;
    // End of variables declaration//GEN-END:variables
}
